version: "3.8"

services:
  postgres:
    container_name: goexampleserver
    image: postgres:14.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/pg/data
  
  go:
    container_name: go
    build:
      context: .
    ports:
      - "127.0.0.1:3000:3000"

volumes:
  dbdata:
